const IPC_CHANNELS = {
  GET_USER_AWEME_LIST: 'GET_USER_AWEME_LIST',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_MULTI_AWEME_DETAILS: 'GET_MULTI_AWEME_DETAILS',
  SELECT_FOLDER: 'SELECT_FOLDER',
  DOWNLOAD_FILE: 'DOWNLOAD_FILE',
  GET_DEFAULT_DOWNLOAD_PATH: 'GET_DEFAULT_DOWNLOAD_PATH',
  // Auto Updater
  CHECK_FOR_UPDATES: 'CHECK_FOR_UPDATES',
  DOWNLOAD_UPDATE: 'DOWNLOAD_UPDATE',
  QUIT_AND_INSTALL: 'QUIT_AND_INSTALL',
  // Auto Updater Events
  UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
  UPDATE_DOWNLOADED: 'UPDATE_DOWNLOADED',
  DOWNLOAD_PROGRESS: 'DOWNLOAD_PROGRESS',
  UPDATE_ERROR: 'UPDATE_ERROR',
  CHECKING_FOR_UPDATE: 'CHECKING_FOR_UPDATE',
  UPDATE_NOT_AVAILABLE: 'UPDATE_NOT_AVAILABLE',
  // Settings
  GET_SETTINGS: 'GET_SETTINGS',
  SAVE_SETTINGS: 'SAVE_SETTINGS'
} as const

const TIKTOK_API_URL = {
  GET_USER_AWEME_LIST: 'https://aggr22-normal-alisg.tiktokv.com/lite/v2/public/item/list/',
  GET_MULTI_AWEME_DETAIL: 'https://api22-core-c-alisg.tiktokv.com/lite/v2/feed/fyp/'
} as const

const DEFAULT_USER_AGENT =
  'com.zhiliaoapp.musically/2023501030 (Linux; U; Android 13; en_US; Pixel 7; Build/TD1A.220804.031; Cronet/58.0.2991.0)'

const TIKTOK_POST_DETAIL_URL_PATTERN =
  /tiktok\.com\/(?:@[A-Za-z0-9._-]+)\/(?:video|photo)\/(\d+)(?:\?.*)?$/

export { IPC_CHANNELS, TIKTOK_API_URL, DEFAULT_USER_AGENT, TIKTOK_POST_DETAIL_URL_PATTERN }
